# THIS ONLY WORK ON 127.0.0.1:3000
RECAPTCHA_PUBLIC_KEY_BIS: '6LdO6R8TAAAAAK4JOgsXtpNz3O-W0xT_DEaqxNMo'
RECAPTCHA_PRIVATE_KEY: "6LdO6R8TAAAAAM7okxh79m94rOYm9yR2lZNYcJrR"

# OFFICE 365
OFFICE365_KEY: '0697591a-bada-4d03-8354-f4ad3dd4493b'                         # Client ID
OFFICE365_SECRET: 'vZ08XLidgRxskGd2kqJzHcd'    # Client Secret

# FACEBOOK
FACEBOOK_KEY: ''
FACEBOOK_SECRET: ''

# GITHUB
GITHUB_KEY: 'c6befc3523d739417860'
GITHUB_SECRET: '8271ba3736027e1e23671d27b2656c9daa4f9868'

# TWITTER
TWITTER_KEY: ''
TWITTER_SECRET: ''