# THIS ONLY WORK ON 127.0.0.1:3000
RECAPTCHA_PUBLIC_KEY: ''
RECAPTCHA_PRIVATE_KEY: "6LdO6R8TAAAAAM7okxh79m94rOYm9yR2lZNYcJrR"

# OFFICE 365
OFFICE365_KEY: '0697591a-bada-4d03-8354-f4ad3dd4493b'
OFFICE365_SECRET: 'vZ08XLidgRxskGd2kqJzHcd'

# Google
GOOGLE_KEY: '0697591a-bada-4d03-8354-f4ad3dd4493b'
GOOGLE_SECRET: 'vZ08XLidgRxskGd2kqJzHcd'

# FACEBOOK
FACEBOOK_KEY: ''
FACEBOOK_SECRET: ''

# GITHUB
GITHUB_KEY: '877d42745b7f05dfe8ed'
GITHUB_SECRET: '7ceda1dc5e454fce4a0c245334fc6bc4efdc5544'

# TWITTER
TWITTER_KEY: ''
TWITTER_SECRET: ''

CALLBACK_URL: "https://79066343.ngrok.io"