application_name:
  default: "mCMS"
email_from:
  default: "from@example.com"
conference_url:
  default: "https://www.appear.in/$room_number$"
open_new_tab_url:
  default: 'true'
use_iframe:
  default: 'true'
email_header:
  default: ""
email_footer:
  default: |-
    You have received this notification because you have either subscribed to it, or are involved in it.