application_name:
  default: "mCMS"
email_from:
  default: "from@example.com"
email_header:
  default: ""
email_footer:
  default: |-
    You have received this notification because you have either subscribed to it, or are involved in it.