application_name:
  default: "mCMS"
email_from:
  default: "from@example.com"
conference_url:
  default: "https://www.appear.in/$room_number$"
open_new_tab_url:
  default: 'true'
use_iframe:
  default: 'true'
user_default_state:
  default: 'false'
remember_for:
  default: 2
timeout_in:
  default: 15
maximum_attempts:
  default: 5
unlock_in:
  default: 1
email_header:
  default: ""
email_footer:
  default: |-
    You have received this notification because you have either subscribed to it, or are involved in it.